Add CI
Draegerwerk/sdc11073 pull request #111
Opened 2023-03-27 08:37 UTC by leon1995

Add CI to run unittests and do release steps on tag push

2023-04-06 07:46 UTC, ldeichmann approved these changes

2023-04-06 13:36 UTC, ldeichmann requested changes

2023-04-06 13:36 UTC, ldeichmann commented on tests/test_client_device.py
Huh?

2023-04-06 13:47 UTC, leon1995 commented on tests/test_client_device.py
thats also a way to get all tests passed. `git revert` does trick

2023-04-11 06:41 UTC, a-kleinf commented on .github/workflows/publish.yml
> +          name: dist
```suggestion
          name: distributions
```

2023-04-11 11:31 UTC, leon1995 commented on .github/workflows/publish.yml
> +          name: dist
done

2023-04-12 07:56 UTC, ldeichmann approved these changes

2023-04-12 13:51 UTC, deichmab-draeger approved these changes

2023-04-13 05:34 UTC, a-kleinf approved these changes

2023-04-13 06:27 UTC, ldeichmann approved these changes

2023-04-13 07:23 UTC, deichmab-draeger approved these changes

2023-04-13 07:25 UTC, merged