Introduce ssl context container
Draegerwerk/sdc11073 pull request #216
Opened 2023-07-21 18:30 UTC by maximilianpilz

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [x] I have added tests to cover my changes.

2023-08-01 12:47 UTC, leon1995 requested changes

2023-08-01 12:53 UTC, deichmab-draeger commented on src/sdc11073/certloader.py
I do not agree. It is a top level functionality needed by user. And the name is fine, it does what it says.

2023-08-01 12:54 UTC, deichmab-draeger commented on src/sdc11073/certloader.py
> +def mk_ssl_contexts_from_folder(ca_folder,
why???

2023-08-01 12:56 UTC, deichmab-draeger submitted a review, later dismissed

2023-08-01 13:23 UTC, leon1995 commented on src/sdc11073/certloader.py
the methods in the file are used for ssl context

2023-08-01 13:25 UTC, leon1995 commented on src/sdc11073/certloader.py
> +def mk_ssl_contexts_from_folder(ca_folder,
because it can be optimized and reduced

2023-08-01 14:53 UTC, deichmab-draeger commented on src/sdc11073/certloader.py
> +def mk_ssl_contexts_from_folder(ca_folder,
It makes / creates something, therefore i think the name is fine. Please suggest something better. 
I doubt that a review on this level makes any sense, btw.

2023-08-28 08:41 UTC, deichmab-draeger approved these changes

2023-08-28 10:17 UTC, merged