fixed matching_services method, add typing to location.py
Draegerwerk/sdc11073 pull request #226
Opened 2023-07-26 14:23 UTC by deichmab-draeger

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [x] I have added tests to cover my changes.

2023-07-27 08:45 UTC, leon1995 requested changes

2023-07-27 08:45 UTC, leon1995 commented on src/sdc11073/location.py
> +    def scope_string(self) -> str:
why not
```python
@property
def scope(self) -> ScopeType:
  ...
```
convert scope to string should be handled in `ScopeType` and not here

2023-07-27 08:45 UTC, leon1995 commented on src/sdc11073/location.py
> +            other = self.__class__.from_scope_string(str(scope_text))
why compare strings? use compare of `ScopeType` instead.

2023-07-27 08:45 UTC, leon1995 commented on src/sdc11073/location.py
check linter findings

2023-08-01 08:27 UTC, deichmab-draeger commented on src/sdc11073/location.py
> +        return self._any_scope_string_matches(service.scopes.text)
done

2023-08-01 08:31 UTC, deichmab-draeger commented on src/sdc11073/location.py
>  class SdcLocation:
I think dataclass has no benefit here. But I simplified the class by 
- renaming member bld to bldng, this makes name mapping obsolete. 
- moved mk_extension_string functionality to LocationContextStateContainer, this is the only user.

2023-08-01 08:33 UTC, deichmab-draeger commented on src/sdc11073/location.py
> +    def mk_extension_string(self) -> str:
moved to LocationContextStateContainer. The name reflects that InstanceIdentifier has an extension_string parameter.

2023-08-01 08:39 UTC, deichmab-draeger commented on src/sdc11073/location.py
> +    def scope_string(self) -> str:
I think it is better located here because ScopesType -> SdcLocation and SdcLocation -> ScopesType conversions then are handled in the same place.

2023-08-01 08:47 UTC, deichmab-draeger commented on src/sdc11073/location.py
> +    def scope_string(self) -> str:
ScopesType contains a list of strings. scopes_string creates only one the one that represents this location.

2023-08-01 10:17 UTC, leon1995 commented on src/sdc11073/location.py
> +            other = self.__class__.from_scope_string(str(scope_text))
no need to cast it to `str` as the parameter type indicates that it is already a string

2023-08-01 10:17 UTC, leon1995 approved these changes

2023-08-01 10:19 UTC, leon1995 requested changes

2023-08-01 10:19 UTC, leon1995 commented on tests/test_sdclocation.py
>      scheme = SdcLocation.scheme  # 'sdc.ctxt.loc'
`SdcLocation.location_detail_root` raises `AttributeError`

2023-08-01 10:19 UTC, leon1995 commented on src/sdc11073/mdib/statecontainers.py
> +    def _mk_extension_string(self, sdc_location: SdcLocation):
missing return type

2023-08-01 11:46 UTC, leon1995 approved these changes

2023-08-01 12:00 UTC, deichmab-draeger commented on src/sdc11073/mdib/statecontainers.py
> +    def _mk_extension_string(self, sdc_location: SdcLocation):
done

2023-08-01 12:01 UTC, leon1995 approved these changes

2023-08-01 12:44 UTC, merged