Fix/binding mdib version
Draegerwerk/sdc11073 pull request #234
Opened 2023-08-09 07:57 UTC by deichmab-draeger

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-08-17 16:18 UTC, a-kleinf requested changes

2023-08-17 16:18 UTC, a-kleinf commented on tutorial/provider/provider.py
>          newEnsState = mgr.getContextState(descriptorContainer.handle)  # this creates a new location state
this comment and also the comment in line 28 are wrong

2023-08-21 08:17 UTC, deichmab-draeger commented on src/sdc11073/mdib/devicemdib.py
>          self.contextStateUpdates[lookup_key] = _TrItem(oldStateContainer, newStateContainer)
added a check.

2023-08-21 08:36 UTC, deichmab-draeger commented on src/sdc11073/roles/contextprovider.py
> +                    if proposed_st.ContextAssociation == ContextAssociation.ASSOCIATED:
Apply automatic disasssociate only on LocationContextState and PatientContextState. 
Regarding the other states: There is no explicit rule I am aware of how to handle them. I think it is better not to change these values.

2023-08-21 11:02 UTC, a-kleinf approved these changes

2023-08-21 12:38 UTC, merged