238 ext extension containerpropertiesextensionnodeproperty comparison is not as expected
Draegerwerk/sdc11073 pull request #239
Opened 2023-08-17 13:41 UTC by leon1995

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-08-23 12:25 UTC, a-kleinf requested changes

2023-08-23 12:39 UTC, leon1995 commented on src/sdc11073/xml_types/xml_structure.py
> +                     xml_diff.diff_trees(val2, val1, {'F': 1}))  # compare right left
not applicable anymore

2023-08-23 12:46 UTC, leon1995 commented on src/sdc11073/xml_types/xml_structure.py
>              return len(self.value) == 0
done

2023-08-23 18:57 UTC, a-kleinf submitted a review, later dismissed

2023-08-24 05:43 UTC, leon1995 commented on tests/test_pmtypes.py
> +                <foo someattr="somevalue"/>
done

2023-08-24 12:50 UTC, a-kleinf approved these changes

2023-08-24 12:50 UTC, merged