fix RUF012 #156
Draegerwerk/sdc11073 pull request #248
Opened 2023-08-31 10:53 UTC by leon1995

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-08-31 10:55 UTC, leon1995 commented
one can check for all occurrences of `RUF102` using `ruff check . --select RUF012`

2023-09-05 13:14 UTC, deichmab-draeger requested changes

2023-09-06 06:13 UTC, leon1995 commented on src/sdc11073/xml_types/dataconverters.py
>                  raise ValueError(f'Value must be list or a tuple, got {type(py_value)}')
done

2023-09-06 09:43 UTC, deichmab-draeger approved these changes

2023-09-06 11:16 UTC, merged