fixed all lint findings that appeared under 4 times
Draegerwerk/sdc11073 pull request #253
Opened 2023-09-01 11:47 UTC by leon1995

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-09-06 10:28 UTC, deichmab-draeger requested changes

2023-09-07 08:45 UTC, leon1995 commented on src/sdc11073/certloader.py
> +        with ca_folder.joinpath(cyphers_file).open(encoding='utf-8') as file:
done

2023-09-07 08:50 UTC, leon1995 commented on src/sdc11073/certloader.py
> +    ca_folder = pathlib.Path(ca_folder)
I expected the normal `FileNotFoundError` in these libraries to give a bit more information, but you are right. done

2023-09-07 08:50 UTC, leon1995 commented on src/sdc11073/httpserver/httpreader.py
>          data.write(head)
done

2023-09-18 08:24 UTC, merged