Fix/use ws addressing 2006
Draegerwerk/sdc11073 pull request #265
Opened 2023-09-21 13:06 UTC by leon1995

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-09-22 08:51 UTC, deichmab-draeger requested changes

2023-09-22 12:28 UTC, leon1995 commented on src/sdc11073/provider/subscriptionmgr_base.py
>                              mdib_version_group,
done

2023-09-22 13:11 UTC, deichmab-draeger approved these changes

2023-09-26 09:05 UTC, deichmab-draeger approved these changes

2023-09-26 09:06 UTC, merged