Modify python versions
Draegerwerk/sdc11073 pull request #274
Opened 2023-10-17 13:30 UTC by leon1995

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-10-17 13:38 UTC, maximilianpilz requested changes

2023-10-17 13:38 UTC, maximilianpilz commented on codecov.yml
> +        # do not notify until at least 20 builds (python versions * os * extension = 6 * 2 * 2 = 24) have been uploaded from the CI pipeline
```suggestion
        # do not notify until at least 24 builds (python versions * os * extension = 6 * 2 * 2 = 24) have been uploaded from the CI pipeline
```

2023-10-17 13:41 UTC, leon1995 commented on codecov.yml
> +        # do not notify until at least 20 builds (python versions * os * extension = 6 * 2 * 2 = 24) have been uploaded from the CI pipeline
done

2023-10-18 12:29 UTC, maximilianpilz approved these changes

2023-10-18 12:29 UTC, merged