alert provider role sends self check one second before time elapsed.
Draegerwerk/sdc11073 pull request #280
Opened 2023-11-01 10:50 UTC by deichmab-draeger

Send self check data a little earlier than SelfCheckPeriod, that helps to avoid timeouts on consumer side. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-11-06 10:50 UTC, leon1995 requested changes

2023-11-06 10:50 UTC, leon1995 commented on CHANGELOG.md
> +-
can be removed I guess

2023-11-07 12:25 UTC, deichmab-draeger commented on CHANGELOG.md
> +-
done

2023-11-08 07:16 UTC, leon1995 approved these changes

2023-11-08 08:45 UTC, merged