use SubElement where possible when creating dom trees
Draegerwerk/sdc11073 pull request #285
Opened 2023-11-16 14:26 UTC by deichmab-draeger

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2023-11-16 14:46 UTC, a-kleinf commented on src/sdc11073/mdib/mdibbase.py
>              node.append(child_node)
I think this must be removed

2023-11-16 15:13 UTC, deichmab-draeger commented on src/sdc11073/mdib/mdibbase.py
>              node.append(child_node)
done

2023-11-17 08:27 UTC, a-kleinf requested changes

2023-11-17 08:27 UTC, a-kleinf commented on tests/test_mdib.py
> +            self.assertTrue('msg' in arg_node.nsmap)
is this needed?

2023-11-17 08:27 UTC, a-kleinf commented on tests/test_mdib.py
> +            self.assertTrue(prefix in arg_node.nsmap)
maybe add
            self.assertEqual(test_data.expected_qname.namespace, arg_node.nsmap[prefix])
            self.assertEqual(test_data.expected_qname.localname, arg_node.text.split(':')[1])

2023-11-17 10:08 UTC, deichmab-draeger commented on tests/test_mdib.py
> +            self.assertTrue('msg' in arg_node.nsmap)
no

2023-11-17 10:14 UTC, deichmab-draeger commented on tests/test_mdib.py
> +            self.assertTrue(prefix in arg_node.nsmap)
done

2023-12-05 07:53 UTC, a-kleinf approved these changes

2023-12-05 08:38 UTC, a-kleinf approved these changes

2023-12-05 08:59 UTC, merged