Feature/split transaction
Draegerwerk/sdc11073 pull request #301
Opened 2023-12-06 15:38 UTC by deichmab-draeger

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [x] I have added tests to cover my changes.

2024-01-22 14:54 UTC, leon1995 requested changes

2024-01-22 15:22 UTC, deichmab-draeger commented on CHANGELOG.md
> +- new interface for transactions: split transaction into different kinds, e.g. descriptor_transaction, metric_state_transaction, etc.
done

2024-01-22 15:28 UTC, deichmab-draeger commented on src/sdc11073/mdib/providermdib.py
> +                             set_determination_time: bool = True) -> AbstractContextManager[
typing.ContextManager is deprecated.

2024-01-22 15:32 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +            raise ValueError(f'cannot create Descriptor {descriptor_handle}, it already exists!')
done

2024-01-22 15:34 UTC, deichmab-draeger commented on src/sdc11073/consumer/consumerimpl.py
> +            time.sleep(1)
I don't think that fixes the problem. Its needs further investigation why waiting for the event is not always sufficient.

2024-01-23 09:34 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        self.descriptor_updates[descriptor_handle] = TransactionItem(orig_descriptor_container, None)
It is easier to do this in process_transaction, because deleting a descriptor means deleting the whole sub tree and according states.

2024-01-23 09:59 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        updates_dict[state_container.DescriptorHandle] = TransactionItem(None, state_container)
You are right. Changed code to use state_container.Handle for context states.

2024-01-23 10:11 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +    def process_transaction(self, set_determination_time: bool) -> TransactionResultProtocol:  # noqa: ARG002
The alternative would be to add a second _transaction_manager im provider mdib without determination time. I think unused parameter is the lesser evil.

2024-01-23 10:16 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +                state_update = updates_dict.get(context_state.Handle)
The error was in add_state, not here.

2024-01-23 10:21 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +class DescriptorTransaction(_TransactionBase):
I prefer not to derive from a protocol.

2024-01-23 10:27 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +                    # R0033: A SERVICE PROVIDER SHALL increment pm:AbstractDescriptor/@DescriptorVersion by one
done, also in other locations.

2024-01-23 10:29 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +                new_state = tr_item.new
done

2024-01-23 10:33 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        proc = TransactionResult()
I considered that, but found no elegant solution.

2024-01-23 10:35 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        return state.is_realtime_sample_array_metric_state
Is handled like a normal MetricState.

2024-01-23 10:42 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle is None:
done

2024-01-23 10:44 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +            raise ValueError('descriptor is not a context descriptor!')
done

2024-01-23 10:47 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        new_state_container.Handle = context_state_handle or uuid.uuid4().hex
Added info to docstring. Keeping it this way makes it easier for user.

2024-01-23 10:51 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions_legacy.py
> +
done

2024-01-23 10:55 UTC, deichmab-draeger commented on src/sdc11073/provider/providerimpl.py
> +        if transaction_result.has_descriptor_updates:
done

2024-01-23 10:55 UTC, deichmab-draeger commented on src/sdc11073/provider/providerimpl.py
> +            states = transaction_result.all_states()
done

2024-01-23 10:57 UTC, deichmab-draeger commented on tests/test_transaction.py
> +        self.mdib_version = self._mdib.mdib_version
done

2024-01-24 09:12 UTC, leon1995 requested changes

2024-01-24 09:12 UTC, leon1995 commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
`if not descriptor_handle:`

2024-01-24 09:12 UTC, leon1995 commented on src/sdc11073/consumer/consumerimpl.py
> +            time.sleep(1)
please write an issue explaining the problem and write the number in the code

2024-01-24 09:12 UTC, leon1995 commented on src/sdc11073/mdib/transactions.py
> +        if context_state_handle in (None, ''):
`if not context_state_handle:`

2024-01-24 12:00 UTC, deichmab-draeger commented on src/sdc11073/consumer/consumerimpl.py
> +            time.sleep(1)
done

2024-01-24 12:01 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +    def process_transaction(self, set_determination_time: bool) -> TransactionResultProtocol:  # noqa: ARG002
that is even worse in my opinion.

2024-01-24 12:01 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if handle in (None, ''):
done

2024-01-24 12:01 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:01 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:01 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:02 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:02 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:02 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if descriptor_handle in (None, ''):
done

2024-01-24 12:02 UTC, deichmab-draeger commented on src/sdc11073/mdib/transactions.py
> +        if context_state_handle in (None, ''):
done

2024-01-24 12:47 UTC, leon1995 approved these changes

2024-01-24 14:49 UTC, leon1995 approved these changes

2024-01-25 09:03 UTC, merged