check if there is at least one subscription if evaluating whether con…
Draegerwerk/sdc11073 pull request #302
Opened 2023-12-11 10:31 UTC by leon1995

…sumer is connected or not

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the [changelog](../CHANGELOG.md) accordingly.
- [ ] I have added tests to cover my changes.

2024-01-22 11:47 UTC, deichmab-draeger requested changes

2024-01-22 11:47 UTC, deichmab-draeger commented on src/sdc11073/consumer/consumerimpl.py
> +    subscription_status = properties.ObservableProperty({})
Keep is_connected an observable. Users might rely on a callback.

2024-01-23 07:38 UTC, leon1995 commented on src/sdc11073/consumer/consumerimpl.py
> +    subscription_status = properties.ObservableProperty({})
done

2024-01-23 13:37 UTC, deichmab-draeger approved these changes

2024-01-23 14:32 UTC, merged